// * CATEGORIES

export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORIES_FAIL = "CATEGORIES_FAIL";

// * ADVISORS

export const CATEGORIES_ADV_REQUEST = "CATEGORIES_ADV_REQUEST";
export const CATEGORIES_ADV_SUCCESS = "CATEGORIES_ADV_SUCCESS";
export const CATEGORIES_ADV_FAIL = "CATEGORIES_ADV_FAIL";

export const UPDATE_ADVISOR_REQUEST = "UPDATE_ADVISOR_REQUEST ";
export const UPDATE_ADVISOR_SUCCESS = "UPDATE_ADVISOR_SUCCESS ";
export const UPDATE_ADVISOR_FAIL = "UPDATE_ADVISOR_FAIL";

// * PAGES

export const PAGE_REQUEST = "PAGE_REQUEST";
export const PAGE_SUCCESS = "PAGE_SUCCESS";
export const PAGE_FAIL = "PAGE_FAIL";

// * USER

export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = "USER_FAIL";

// * E LEARNING

export const ELEARNING_REQUEST = "ELEARNING_REQUEST";
export const ELEARNING_SUCCESS = "ELEARNING_SUCCESS";
export const ELEARNING_FAIL = "ELEARNING_FAIL";

// * BLOGS

export const BLOG_REQUEST = "BLOG_REQUEST";
export const BLOG_SUCCESS = "BLOG_SUCCESS";
export const BLOG_FAIL = "BLOG_FAIL";

export const SINGLE_BLOG_REQUEST = "SINGLE_BLOG_REQUEST";
export const SINGLE_BLOG_SUCCESS = "SINGLE_BLOG_SUCCESS";
export const SINGLE_BLOG_FAIL = "SINGLE_BLOG_FAIL";

// * ADMIN

export const ADMIN_ADVISORS_REQUEST = "ADMIN_ADVISORS_REQUEST";
export const ADMIN_ADVISORS_SUCCESS = "ADMIN_ADVISORS_SUCCESS";
export const ADMIN_ADVISORS_FAIL = "ADMIN_ADVISORS_FAIL";

export const ADMIN_CLIENTS_REQUEST = "ADMIN_CLIENTS_REQUEST";
export const ADMIN_CLIENTS_SUCCESS = "ADMIN_CLIENTS_SUCCESS";
export const ADMIN_CLIENTS_FAIL = "ADMIN_CLIENTS_FAIL";

export const ADMIN_CATEGORIES_REQUEST = "ADMIN_CATEGORIES_REQUEST";
export const ADMIN_CATEGORIES_SUCCESS = "ADMIN_CATEGORIES_SUCCESS";
export const ADMIN_CATEGORIES_FAIL = "ADMIN_CATEGORIES_FAIL";

export const FEEDBACKS_REQUEST = "FEEDBACKS_REQUEST";
export const FEEDBACKS_SUCCESS = "FEEDBACKS_SUCCESS";
export const FEEDBACKS_FAIL = "FEEDBACKS_FAIL";

export const FORM_FEEDBACKS_REQUEST = "FORM_FEEDBACKS_REQUEST";
export const FORM_FEEDBACKS_SUCCESS = "FORM_FEEDBACKS_SUCCESS";
export const FORM_FEEDBACKS_FAIL = "FORM_FEEDBACKS_FAIL";

export const SINGLE_FEEDBACK_REQUEST = "SINGLE_FEEDBACK_REQUEST";
export const SINGLE_FEEDBACK_SUCCESS = "SINGLE_FEEDBACK_SUCCESS";
export const SINGLE_FEEDBACK_FAIL = "SINGLE_FEEDBACK_FAIL";
