export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORIES_FAIL = "CATEGORIES_FAIL";

export const CATEGORIES_ADV_REQUEST = "CATEGORIES_ADV_REQUEST";
export const CATEGORIES_ADV_SUCCESS = "CATEGORIES_ADV_SUCCESS";
export const CATEGORIES_ADV_FAIL = "CATEGORIES_ADV_FAIL";

export const PAGE_REQUEST = "PAGE_REQUEST";
export const PAGE_SUCCESS = "PAGE_SUCCESS";
export const PAGE_FAIL = "PAGE_FAIL";

export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = "USER_FAIL";

export const ELEARNING_REQUEST = "ELEARNING_REQUEST";
export const ELEARNING_SUCCESS = "ELEARNING_SUCCESS";
export const ELEARNING_FAIL = "ELEARNING_FAIL";

export const ADMIN_CATEGORIES_REQUEST = "ADMIN_CATEGORIES_REQUEST";
export const ADMIN_CATEGORIES_SUCCESS = "ADMIN_CATEGORIES_SUCCESS";
export const ADMIN_CATEGORIES_FAIL = "ADMIN_CATEGORIES_FAIL";

export const UPDATE_ADVISOR_REQUEST = "UPDATE_ADVISOR_REQUEST ";
export const UPDATE_ADVISOR_SUCCESS = "UPDATE_ADVISOR_SUCCESS ";
export const UPDATE_ADVISOR_FAIL = "UPDATE_ADVISOR_FAIL";
